#!/bin/bash

echox() {
  printf "[\033[1;32minitial-setup\033[0m] %s\n" "$1"
}

if [ -z "$(command -v devbox)" ]; then
  echox "Installing devbox"
  curl -fsSL https://get.jetify.com/devbox | bash -s -- -f
  eval "$(devbox global shellenv)"
else
  echox "devbox already installed"
fi

echox "Setting up devbox shell completion"
devbox completion zsh >/opt/homebrew/share/zsh/site-functions/_devbox
