#!/bin/bash

echox() {
  printf "[\033[1;32mrefresh-dev-packages\033[0m] %s\n" "$1"
}

echox "Symlinking tmux config"
ln -s -f "$HOME/.tmux/.tmux.conf" "$HOME/.tmux.conf"

echox "Touching $HOME/.secrets/env"
mkdir -p "$HOME/.secrets"
touch "$HOME/.secrets/env"
