#!/bin/bash

set -e

echox() {
  printf "[\033[1;32minstall-packages\033[0m] %s\n" "$1"
}
install_brew() {
  if test ! "$(which brew)"; then
    echox "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    echox "Adding homebrew to shell PATH"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

install_brew
echox "Updating brew"
brew update
set +e
brew bundle --force --file="$HOME/Brewfile"
set -e

# GH extensions
echox "Installing gh extensions"
gh auth status >/dev/null 2>&1 || gh auth login
gh extension install ilaif/gh-prx || true
gh extension install mislav/gh-branch

# npm
echox "Install global npm packages"
export PATH="$HOME/Library/pnpm/bin:$PATH"
pnpm add -g @githubnext/github-copilot-cli
pnpm add -g @escape.tech/mookme
pnpm add -g ccstatusline

# Other apps
echox "Other apps to install:"
echox "* Login to google drive"
echox "* Import settings from personal-drive/dev/environment/raycast.export"
echox "* Open RayCast and configure"
echox "* Open 1Password and configure"
echox "* Open VSCode and login to Settings & Sync"
