command_timeout = 5000

[character]
#success_symbol = "[\uf054](white)" # 
#vicmd_symbol = "[\ue62b](white)" # 
#error_symbol = "[\uf467](red)" # 

[gcloud]
disabled = true

[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[docker_context]
disabled = true
